/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Checkbox: typeof import('./src/components/ui/Checkbox.vue')['default']
    copy: typeof import('./src/components/ui/RadioButton copy.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Input: typeof import('./src/components/ui/Input.vue')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ui/Select.vue')['default']
    ToggleSwitch: typeof import('./src/components/ui/ToggleSwitch.vue')['default']
  }
}
